# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [5]:
import numpy as np
np.__version__

'1.21.5'

2) Создать нулевой вектор размера 10

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [23]:
# np.linspace(7, 7, 7)  // Формат float32
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [27]:
np.arange(10,101)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [46]:
arr5 = np.random.random(5,)
print(arr5)
arr5 = arr5[::-1]
print(arr5)

[0.315694   0.42002083 0.89907974 0.40610588 0.08153422]
[0.08153422 0.40610588 0.89907974 0.42002083 0.315694  ]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [67]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [62]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [85]:
arr8 = np.diag([1, 2, 3, 4])
arr8[arr8 == 0] = 7
print(arr8)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [75]:
np.diag([0, 1, 2, 3, 4])

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [112]:
arr10 = np.random.random((10,10))
new_arr10 = arr10 - np.mean(arr10, axis = 1)

arr10

array([[0.84374374, 0.28927171, 0.14283381, 0.11835764, 0.40524362,
        0.05573133, 0.47888479, 0.20129839, 0.5534552 , 0.27435778],
       [0.23907861, 0.78299291, 0.60355015, 0.95017211, 0.51856495,
        0.59856958, 0.91226508, 0.17757241, 0.79151067, 0.75752226],
       [0.39584787, 0.97553597, 0.84330106, 0.79472108, 0.13331675,
        0.22924914, 0.43395936, 0.74769867, 0.95916357, 0.76790598],
       [0.19470024, 0.29167245, 0.17167492, 0.94459992, 0.77310492,
        0.09047576, 0.90323552, 0.48404685, 0.84411449, 0.21953414],
       [0.17574706, 0.12738537, 0.56755443, 0.74070505, 0.5003157 ,
        0.29450175, 0.78475018, 0.44840616, 0.75013462, 0.49114654],
       [0.33892582, 0.29346868, 0.04068095, 0.35974118, 0.90850904,
        0.40977767, 0.84928324, 0.24941808, 0.09731838, 0.20644794],
       [0.45824104, 0.27549614, 0.24900252, 0.26053913, 0.98792277,
        0.26215581, 0.47766647, 0.98367262, 0.11020337, 0.83061885],
       [0.3041647 , 0.68640891, 0.9517513

In [113]:
new_arr10

array([[ 0.50742594, -0.34390816, -0.48523613, -0.37335828, -0.08282107,
        -0.31962577, -0.01066708, -0.48123186, -0.08022035, -0.27089773],
       [-0.09723919,  0.14981303, -0.02451979,  0.45845619,  0.03050026,
         0.22321248,  0.42271321, -0.50495785,  0.15783512,  0.21226676],
       [ 0.05953007,  0.3423561 ,  0.21523111,  0.30300516, -0.35474794,
        -0.14610796, -0.05559251,  0.06516841,  0.32548802,  0.22265047],
       [-0.14161756, -0.34150743, -0.45639502,  0.452884  ,  0.28504023,
        -0.28488134,  0.41368365, -0.19848341,  0.21043894, -0.32572136],
       [-0.16057074, -0.5057945 , -0.06051552,  0.24898913,  0.01225101,
        -0.08085535,  0.29519831, -0.2341241 ,  0.11645907, -0.05410897],
       [ 0.00260801, -0.3397112 , -0.58738899, -0.13197474,  0.42044436,
         0.03442058,  0.35973137, -0.43311218, -0.53635717, -0.33880756],
       [ 0.12192324, -0.35768373, -0.37906743, -0.23117679,  0.49985809,
        -0.11320129, -0.0118854 ,  0.30114237

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [118]:
arr11 = np.random.randint(10, size = (10, 10))
new_arr11 = arr11 - np.median(arr11, axis = 0)

In [119]:
arr11

array([[2, 3, 5, 8, 3, 5, 5, 7, 1, 6],
       [3, 5, 9, 2, 6, 1, 6, 7, 2, 5],
       [5, 2, 5, 4, 2, 9, 1, 2, 0, 5],
       [9, 1, 3, 8, 7, 7, 4, 5, 1, 3],
       [3, 9, 9, 2, 0, 1, 5, 4, 0, 8],
       [7, 6, 9, 1, 4, 6, 3, 9, 7, 7],
       [7, 5, 9, 3, 0, 3, 1, 4, 6, 7],
       [8, 4, 1, 1, 1, 2, 9, 6, 6, 8],
       [0, 9, 0, 5, 8, 2, 3, 0, 3, 8],
       [6, 5, 9, 3, 4, 1, 1, 4, 5, 1]])

In [121]:
np.median(arr11, axis = 0)

array([5.5, 5. , 7. , 3. , 3.5, 2.5, 3.5, 4.5, 2.5, 6.5])

In [120]:
new_arr11

array([[-3.5, -2. , -2. ,  5. , -0.5,  2.5,  1.5,  2.5, -1.5, -0.5],
       [-2.5,  0. ,  2. , -1. ,  2.5, -1.5,  2.5,  2.5, -0.5, -1.5],
       [-0.5, -3. , -2. ,  1. , -1.5,  6.5, -2.5, -2.5, -2.5, -1.5],
       [ 3.5, -4. , -4. ,  5. ,  3.5,  4.5,  0.5,  0.5, -1.5, -3.5],
       [-2.5,  4. ,  2. , -1. , -3.5, -1.5,  1.5, -0.5, -2.5,  1.5],
       [ 1.5,  1. ,  2. , -2. ,  0.5,  3.5, -0.5,  4.5,  4.5,  0.5],
       [ 1.5,  0. ,  2. ,  0. , -3.5,  0.5, -2.5, -0.5,  3.5,  0.5],
       [ 2.5, -1. , -6. , -2. , -2.5, -0.5,  5.5,  1.5,  3.5,  1.5],
       [-5.5,  4. , -7. ,  2. ,  4.5, -0.5, -0.5, -4.5,  0.5,  1.5],
       [ 0.5,  0. ,  2. ,  0. ,  0.5, -1.5, -2.5, -0.5,  2.5, -5.5]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [164]:
arr12 = np.random.randint(5, size = (5, 5))
max = arr12.max(axis = 1, keepdims=True)
min = arr12.min(axis = 1, keepdims=True)
np.hstack((arr12, max, min))
# np.concatenate(arr12, max, axis = 1)

array([[2, 4, 3, 0, 3, 4, 0],
       [4, 0, 4, 3, 4, 4, 0],
       [1, 3, 4, 4, 2, 4, 1],
       [0, 3, 0, 0, 2, 3, 0],
       [0, 1, 0, 0, 1, 1, 0]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [182]:
arr13 = np.arange(1,51)
even = arr13[arr13 % 2 == 0]
non_even = arr13[arr13 % 2 != 0]
pr = even * non_even
pr

array([   2,   12,   30,   56,   90,  132,  182,  240,  306,  380,  462,
        552,  650,  756,  870,  992, 1122, 1260, 1406, 1560, 1722, 1892,
       2070, 2256, 2450])

In [217]:
a =np.mat(np.arange(1,50)[1::2]).reshape(4,6)
b =np.mat(np.arange(1,50)[2::2]).reshape(6,4)

print(a*b)

[[1246 1330 1414 1498]
 [2902 3130 3358 3586]
 [4558 4930 5302 5674]
 [6214 6730 7246 7762]]


In [220]:
a

matrix([[ 2,  4,  6,  8, 10, 12],
        [14, 16, 18, 20, 22, 24],
        [26, 28, 30, 32, 34, 36],
        [38, 40, 42, 44, 46, 48]])

In [193]:
b

matrix([[ 3,  5,  7,  9],
        [11, 13, 15, 17],
        [19, 21, 23, 25],
        [27, 29, 31, 33],
        [35, 37, 39, 41],
        [43, 45, 47, 49]])

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 